expo_package_path = Pod::Executable.execute_command(
  'node',
  ['-p', <<-'NODE', __dir__]
(() => {
  try {
    return require.resolve("expo/package.json", { paths: [process.argv[1]] });
  } catch (e) {
    return "";
  }
})()
NODE
).strip

expo_autolinking_enabled = false
if !expo_package_path.empty?
  require File.join(File.dirname(expo_package_path), "scripts/autolinking")
  expo_autolinking_enabled = true
else
  Pod::UI.warn "Expo package not found; skipping Expo autolinking.".yellow
end

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# platform :ios, min_ios_version_supported
platform :ios, 17.0
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


target 'GodotTest' do
  if expo_autolinking_enabled
    use_expo_modules!
    post_integrate do |installer|
      begin
        expo_patch_react_imports!(installer)
      rescue => e
        Pod::UI.warn e
      end
    end
  end

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
